apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-pro
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'jefferson.pino@gmail.com'
    privateKeySecretRef: 
      name: letsencrypt-pro
    http01: {}